<?php echo $this->doctype() ?>
<html>
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
<?php if ($this->dojo()->isEnabled()){
    $this->dojo()->setLocalPath('/java/dojo/dojo.js')
                 ->addStyleSheetModule('dijit.themes.claro');
    echo $this->dojo();
   }
?>
    <?php echo $this->headScript() ?>

</head>
<body class="claro">
    <?php echo $this->layout()->content ?>
    <?php echo $this->inlineScript() ?>
</body>
</html>
